name: Release app

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [{ name: "windows", image: "windows-latest" }]

    runs-on: ${{ matrix.os.image }}

    steps:
      - name: Github checkout
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - run: npm install

      - name: Publish app
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: npm run publish
